sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull selenium/hub
- docker run -d -P --name selenium-hub selenium/hub
- docker run -d -P --link selenium-hub:hub selenium/node-chrome-debug 
